# Generated by Django 2.2 on 2019-05-02 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190426_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateTimeField(default=django.utils.timezone.now)),
                ('roleOfUser', models.CharField(max_length=9)),
                ('ABN', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='medicare',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
