# Generated by Django 2.2 on 2019-05-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190502_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleOfUser',
            field=models.CharField(choices=[('1', 'Candidate'), ('2', 'Employee'), ('3', 'Education')], max_length=50),
        ),
    ]
