# Generated by Django 2.2 on 2019-05-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190502_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
