# Generated by Django 2.1.7 on 2019-05-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_experience',
            old_name='fname',
            new_name='fist_name',
        ),
    ]
