# Generated by Django 2.1.7 on 2019-05-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('comment_box', models.CharField(max_length=50)),
                ('medicare', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='employer_experience',
        ),
    ]
