# Generated by Django 2.2 on 2019-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='nameOfEmployer',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
