# Generated by Django 2.1.7 on 2019-05-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190514_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_experience',
            old_name='company',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employer_experience',
            old_name='contribution',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employer_experience',
            old_name='fist_name',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employer_experience',
            old_name='sname',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employer_experience',
            name='ltime',
        ),
        migrations.RemoveField(
            model_name='employer_experience',
            name='stime',
        ),
    ]
