# Generated by Django 2.1.7 on 2019-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_medicare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='user',
            field=models.DecimalField(decimal_places=0, max_digits=10000, unique=True),
        ),
    ]
