# Generated by Django 2.1.7 on 2019-05-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190514_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_experience',
            name='id',
        ),
        migrations.AddField(
            model_name='employer_experience',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User'),
            preserve_default=False,
        ),
    ]
