# Generated by Django 2.2 on 2019-05-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190528_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetails',
            name='comment_box',
        ),
    ]
