# Generated by Django 2.1.7 on 2019-05-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190515_1217'),
        ('blog', '0002_dataentry_nameofemployer'),
    ]

    operations = [
    ]
