# Generated by Django 2.1.7 on 2019-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20190528_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='nameOfEmployer',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='fname',
            field=models.CharField(default='hi', max_length=50),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='sname',
            field=models.CharField(default='hi', max_length=50),
        ),
    ]
