# Generated by Django 2.1.7 on 2019-05-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190528_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sname',
            field=models.CharField(max_length=50),
        ),
    ]
