# Generated by Django 2.2 on 2019-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=1000)),
                ('idOfCandidate', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('idOfEmployer', models.DecimalField(decimal_places=0, max_digits=10000)),
            ],
        ),
    ]
