# Generated by Django 2.1.7 on 2019-05-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190528_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='instituteName',
            field=models.CharField(default='abc news', max_length=50),
            preserve_default=False,
        ),
    ]
