# Generated by Django 2.2 on 2019-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_dataentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='entry',
            field=models.TextField(),
        ),
    ]
