# Generated by Django 2.1.7 on 2019-05-09 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190508_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ltime', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=50)),
                ('contribution', models.CharField(max_length=50)),
                ('comment_box', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='roleOfUser',
            field=models.CharField(choices=[('1', 'Candidate'), ('2', 'Employer'), ('3', 'Education')], max_length=50),
        ),
    ]
