# Generated by Django 2.1.7 on 2019-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190509_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_experience',
            name='fname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_experience',
            name='medicare',
            field=models.DecimalField(decimal_places=0, default='', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_experience',
            name='sname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
