# Generated by Django 2.1.7 on 2019-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190509_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_experience',
            name='medicare',
            field=models.CharField(max_length=50),
        ),
    ]
