# Generated by Django 2.1.7 on 2019-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190509_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_experience',
            name='medicare',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
