# Generated by Django 2.1.7 on 2019-05-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190509_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_experience',
            name='medicare',
        ),
    ]
