# Generated by Django 2.1.7 on 2019-05-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_employer_experience_medicare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_experience',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='employer_experience',
            name='sname',
        ),
    ]
