# Generated by Django 2.1.7 on 2019-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190509_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_experience',
            name='fname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_experience',
            name='sname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
