# Generated by Django 2.2 on 2019-05-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190425_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
