# Generated by Django 2.1.7 on 2019-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='unqiue',
        ),
        migrations.AddField(
            model_name='employee',
            name='unique',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
